### ISSUE TITLE
[Feature] Switch llm

### ISSUE THREAD

**Issue by BenutzerEinsZweiDrei** [ogios/huggingchat-api#1]
hugchat_api is using open assistant. Llamda could be available. I didnt see any option to change llm with your api.

Take a look here.

https://github.com/Soulter/hugging-chat-api/blob/723f3418427cb356e987a35aa7264ba33cd127f3/src/hugchat/hugchat.py#L220

**Comment by ogios** [comment]
added
```python
from hugchat_api.core import ListBots
from hugchat_api import HuggingChat

HUG = HuggingChat(max_thread=1)
bot = HUG.getBot(email=EMAIL, cookies=cookies, model=ListBots.META_70B_HF)
```

`ListBots.<Bot Name>`

**Comment by BenutzerEinsZweiDrei** [comment]
Thanks a lot that was rly fast.

I thought i starred alrdy but i just forked. Now also starred.
